import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ZALS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl font-bold">Zals</h1>
      <p className="text-black-50">TEXT BLACK 50</p>
      <p className="text-white-0">TEXT WHITE 0</p>
      <p className="text-error-50">TEXT ERROR 50</p>
      <p className="text-warning-50">TEXT WARNING 50</p>
      <p className="text-success-50">TEXT SUCCESS 50</p>
    </>
  );
}
